spring.application.name=techstore
spring.datasource.url=jdbc:h2:mem:techstoredb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=VGhpcyBpcyBhIHN1cGVyIHNlY3JldCBrZXkgZm9yIFRlY2hTdG9yZSBKV1QgdG9rZW5zIC0gQ1MyMDMxIDIwMjYh
jwt.expiration=86400000
springdoc.default-produces-media-type=application/json
